---
- name: Install MySQL
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - mariadb
    - mariadb-server

- name: Start MySQL Server
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Check DB
  shell: "mysql -e 'SHOW DATABASES;' | grep {{ db_name }}"
  register: dbstatus
  ignore_errors: yes

- name: Create DB
  shell: "mysql -e 'CREATE DATABASE {{ db_name }};'"
  when: dbstatus.stdout == ""

- name: Create User
  shell: "mysql -e \"GRANT ALL ON wordpress.* TO '{{ db_user }}'@'%' IDENTIFIED BY '{{ db_password }}'\";"
  when: dbstatus.stdout == ""
